A* algorithm for AI units
moddio/taro2 pull request #395
Opened 2023-05-12 15:59 UTC by PineappleBrain

Added A* algorithm for AI
- The algorithm will work for fight, move. Flee will keep simple
- The algorithm works based on grid

Video
https://github.com/moddio/taro2/assets/62375288/2c361d19-ffda-4fc8-a701-eed2be3a2a40

2023-05-22 15:07 UTC, sloont requested changes
This is a phenomenal PR, pb! I may have some more things to say after the first round of revisions, but all in all I don't want to change to much because its done so well.

I would request, that in addition to the requested changes, you take some of the more logic/iteration heavy places in the code and leave some comments that resolve to explain what certain things are doing.

Mostly, comments are necessary for these things:

- When we're doing math, what are we trying to calculate and what is it for
- local variables like:
```
let openList = [];
let closeList = [];
let tempPath = [];
```
    - what are they used for?
    - when we iterate with them, why?
    - when we add to or remove from them, why?

It took me a little while just to figure out how everything was working and I'm still not sure I'm there 100%. Comments will help massively.

2023-05-23 05:25 UTC, PineappleBrain commented on src/gameClasses/components/unit/AIComponent.js
> +						closeList.splice(i, 1);
I just found that the time complexity of Array.splice(i, 1) is O(n) not O(1).
That sentence was originally designed for reduce the size of closeList after putting the item to tempPath, but it will cost even more time to process so I will just remove that sentence.

2023-05-23 05:26 UTC, PineappleBrain commented on src/gameClasses/components/unit/AIComponent.js
> +		openList.push(JSON.parse(JSON.stringify({current: unitTilePosition, parent: {x: -1, y: -1}, totalHeuristic: 0})));
I will use _.cloneDeep() instead of JSON for all instances

2023-05-23 05:28 UTC, PineappleBrain commented on src/gameClasses/components/unit/AIComponent.js
> +					if (!nodeFound) {
It was designed to first check if the node exist in openList. If not, then check closeList. If not then create a new node in openList. The code works as it follows the order but it will check !nodeFound 2 times if it already exist in the openList.
![image](https://github.com/moddio/taro2/assets/62375288/f12930a1-78ba-45b1-a8f2-202b221c1681)
Hence, I will use a for loop to iterate it and break.

2023-05-23 05:30 UTC, PineappleBrain commented on src/gameClasses/components/unit/AIComponent.js
> +								if (this.path.length > 0 && Math.sqrt(Math.pow(this.path[this.path.length - 1].x * taro.map.data.tilewidth - unit._translate.x, 2) + Math.pow(this.path[this.path.length - 1].y * taro.map.data
![image](https://github.com/moddio/taro2/assets/62375288/22b2db00-91bf-40d7-8bd1-3426f9141718)
I think the exist code related to power is good as it store the temporary value.
I will use a similar structure.

2023-05-23 14:25 UTC, sloont commented on src/gameClasses/components/unit/AIComponent.js
> +						closeList.splice(i, 1);
> I just found that the time complexity of Array.splice(i, 1) is O(n) not O(1). That sentence was originally designed for reduce the size of closeList after putting the item to tempPath, but it will cost even more time to process so I will just remove that sentence.

i think its best to just remove because it gets removed at the end of the method anyway, but i guess my question was, did you mean to do `closeList.splice(0, 1)`?

2023-05-24 04:18 UTC, PineappleBrain commented on src/gameClasses/components/unit/AIComponent.js
> +		let wallMap = JSON.parse(JSON.stringify(taro.map.data.layers[3].data)); // wall
I made a deep copy for the wall layer and stored it in taro.map.data.wallMap
It is an array and could be directly retrieved by the script, and I think it would be updated when the map is updated as it is put in "load" of mapComponent.js (Not tested bc localhost cannot update map)

Also I saved taro.map.data as mapData in some of the functions in AIComponent.js so it do not need to get the object inside object every time.

2023-05-30 14:04 UTC, sloont approved these changes

2023-05-30 14:04 UTC, merged