Added getDialogueByDialogueName function
moddio/taro2 pull request #430
Opened 2023-06-11 04:44 UTC by PineappleBrain

Convenient! So you can composite a string and use this function.

2023-06-11 20:18 UTC, m0dE commented
Can you explain the usecase for this? Ideally, you should be able to reference Dialogue by global variable / entity variable

2023-06-12 03:41 UTC, PineappleBrain commented
It can benefit games that widely use dialogue.
---
UC1
A game that with quest or challenge. Lets say it have 100 quest, and each is unique.
Then the create can use `\`dialogue${num}\`` to get the dialogue.
---
UC2
A game with story
Then create can play dialogues page by page `\`dialogue${num++}\`` instead of clicking many times

Altho dialogue can use global variable but it is not very convenient.
JSON array is also having poor performance and junior creators dont know how to use
Referencing a dialogue is good idea. But not referencing many dialogues as creators still need to update follow up dialogue or similar setting with glob one by one which is the having same time cost.

So It seems not very friendly to store the hashed key one by one for dialogues.

Similar idea I want to implement in state of entity too. Im sure some creators have need on it

2023-06-13 23:31 UTC, 420kyle69 requested changes

2023-06-13 23:31 UTC, 420kyle69 commented on src/gameClasses/components/script/VariableComponent.js
> +						console.log(dialogues[id].name, name);
You should remove console.log().

2023-06-18 14:18 UTC, PineappleBrain commented
Use dynamically generated dialogue content would be a better option instead

2023-06-18 14:18 UTC, closed without merging