add 'getMapTileId'
moddio/taro2 pull request #458
Opened 2023-06-23 23:33 UTC by VietnamNeko

2023-06-27 13:38 UTC, sloont requested changes

2023-06-27 13:38 UTC, sloont commented on src/gameClasses/components/script/VariableComponent.js
> +					if (map && x && y && layer && layer >= 0 && layer < 4) {
`x`, `y`, and `layer` can be `0`, so you cannot just check if the value is falsy.

2023-06-27 13:38 UTC, sloont commented on src/gameClasses/components/script/VariableComponent.js
> +
probably want this to use `script.errorLog` if/when this fails so that the client has feedback about the failure

2023-06-27 13:57 UTC, Grenagar commented on src/gameClasses/components/script/VariableComponent.js
> +					if (map && x && y && layer && layer >= 0 && layer < 4) {
check 'editMapTile' action inside actionComponent, we tried to make with out any possible errors

2023-08-09 19:00 UTC, sloont approved these changes

2023-08-09 19:00 UTC, merged