Feat add debug draw and try to fix strange behaviors
moddio/taro2 pull request #507
Opened 2023-07-27 14:35 UTC by moe-moe-pupil

2023-07-27 16:30 UTC, sloont requested changes

2023-07-27 16:30 UTC, sloont commented on src/index.ejs
> +<canvas id="debug-canvas" width="200" height="200" style="position: absolute;top:0;right:0;z-index:100;display: none;"></canvas>
`index.ejs` only gets loaded when running taro standalone. we would have to add this html to the document that gets served from the backend

2023-08-01 15:26 UTC, sloont requested changes

2023-08-01 15:26 UTC, sloont commented on ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts
> +					const newRenderer = new Box2dDebugDraw(box2D, new Box2dHelpers(box2D), ctx, 32).constructJSDraw();
should this line have scale of `30` instead of `32`?

2023-08-03 05:59 UTC, moe-moe-pupil commented on ts/engine/components/physics/box2d/debugDrawWrapper/box2dwasmDebugDraw.ts
> +		this.context.beginPath();
closePath() connects the first point with the last point, it seems not necessary

2023-08-03 06:00 UTC, moe-moe-pupil commented on ts/engine/components/physics/box2d/debugDrawWrapper/box2dwasmDebugDraw.ts
> +			this.context.beginPath();
closePath() connects the first point with the last point, it seems not necessary

2023-08-03 06:01 UTC, moe-moe-pupil commented on ts/engine/components/physics/box2d/debugDrawWrapper/box2dwasmDebugDraw.ts
> +		this.context.fillStyle(colNum, 0.5);
yep, ur right, it seems much better now,
![image](https://github.com/moddio/taro2/assets/42713208/5b84c7a7-3ea3-4094-983b-77925a9dee70)

2023-08-03 06:02 UTC, moe-moe-pupil commented on ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts
> +					const newRenderer = new Box2dDebugDraw(box2D, new Box2dHelpers(box2D), ctx, 32).constructJSDraw();
thanks, I changed it

2023-08-03 14:38 UTC, sloont approved these changes

2023-08-07 12:52 UTC, sloont approved these changes

2023-08-07 16:26 UTC, merged